_target_: sbto.sim.randomize.RandomizeRollout

cfg:
  _target_: sbto.sim.randomize.ConfigRandomizeRollout


  rand_t_knots: 0
  scale_q: 0.
  scale_v: 0.

  obj_x_range: [0., 0.]
  obj_y_range: [0., 0.]
  obj_z_range: [0., 0.]
  obj_w_range: [0., 0.]

  max_base_pos_dist: 0.
  max_base_quat_dist: 0.
  max_grav_quat_dist: 0.
  
  _N_rollout_steps: 30
  _N_max_it: 100
  _N_samples: 256
