_target_: sbto.solvers.pcboc0.PCBOC
cfg:
  _target_: sbto.solvers.pcboc0.ConfigPCBOC
  N_samples: 1024
  N_it: 100
  sigma0: 1.
  quasi_random: False
  seed: 0
  sampler: normal

  beta: 1.e-1
  noise_model: "coordinate"
  delta: 0.7
  dt: 0.1
  kernel: "cosine"
  kappa: 0.007
  alpha_p: 0.1
  alpha: 1.0
  alpha_incr: 1.e-3
  cluster_frac: 0.025
  repulsion: 0.02